name: Argo CD GitOps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Push the image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            abdullahhamada7/go-app:${{ github.sha }}
            abdullahhamada7/go-app:latest

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag
        run: |
          CHART_DIR="chart"
          VALUES_FILE="${CHART_DIR}/values.yaml"
          NEW_IMAGE_TAG=${{ github.sha }}

          echo "Updating image tag in $VALUES_FILE to $NEW_IMAGE_TAG"

          sed -i "s/^  tag: .*/  tag: ${NEW_IMAGE_TAG}/" "$VALUES_FILE"
          grep 'tag:' "$VALUES_FILE"

      - name: Commit and push changes
        run: |
          CHART_DIR="chart"
          VALUES_FILE="${CHART_DIR}/values.yaml"

          git config --global user.name "abdullah-hamada7"
          git config --global user.email "abdullah-hamada7@gmail.com"

          git add "$VALUES_FILE"
          git commit -m "updating image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push
